In [16]:
import re
import pandas as pd

In [17]:
f =open('WhatsApp Chat with Campus(X).txt','r',encoding='utf-8')

In [18]:
data =f.read()

In [19]:
print(data)

31/07/2019, 19:10 - Nitish Singh: Welcome everyone
31/07/2019, 19:11 - Nitish Singh: Session starts shortly
31/07/2019, 19:12 - CXM11 Shantanu Shubham: Good evening sir
31/07/2019, 19:13 - CXM46 Kaushal Agarwal: Good evening
31/07/2019, 19:14 - Nitish Singh: Sharing the meeting link
31/07/2019, 19:15 - Nitish Singh: Timing will be shared soon
31/07/2019, 19:16 - CXM11 Shantanu Shubham: Thank you sir
31/07/2019, 19:16 - CXM46 Kaushal Agarwal: Okay sir
31/07/2019, 19:17 - Nitish Singh: If you have queries ask here
31/07/2019, 19:18 - CXM48 Anjali: Sure sir
31/07/2019, 19:20 - Nitish Singh: Resume reviews begin tomorrow
31/07/2019, 19:22 - CXM43 Bhavna Kumari: Looking forward to it
31/07/2019, 19:25 - Nitish Singh: Please fill the form
31/07/2019, 19:28 - CXM11 Shantanu Shubham: Done
31/07/2019, 19:30 - CXM46 Kaushal Agarwal: Submitted
01/08/2019, 10:00 - Nitish Singh: Today's topic is LinkedIn
01/08/2019, 10:05 - CXM48 Anjali: Great
01/08/2019, 10:10 - CXM43 Bhavna Kumari: Excited
01/08/2019, 10:15 - Nitish Singh: Keep your profiles ready
01/08/2019, 10:20 - CXM11 Shantanu Shubham: Sure
01/08/2019, 10:25 - Nitish Singh: Session starts in 5 mins
01/08/2019, 10:30 - Nitish Singh: Session started
01/08/2019, 10:45 - CXM46 Kaushal Agarwal: Useful tips
01/08/2019, 10:50 - CXM48 Anjali: Learned a lot
01/08/2019, 11:00 - Nitish Singh: Recording will be shared
01/08/2019, 11:05 - CXM43 Bhavna Kumari: Thank you sir
02/08/2019, 17:00 - Nitish Singh: Profile reviews begin now
02/08/2019, 17:10 - CXM11 Shantanu Shubham: Ready
02/08/2019, 17:20 - CXM46 Kaushal Agarwal: Waiting
02/08/2019, 17:30 - Nitish Singh: Starting with Kaushal

In [21]:
pattern = '\d{1,2}/\d{1,2}/\d{2,4},\s\d{1,2}:\d{2}\s-\s'

In [22]:
messages = re.split(pattern,data)[1:]
messages

['Nitish Singh: Welcome everyone\n',
 'Nitish Singh: Session starts shortly\n',
 'CXM11 Shantanu Shubham: Good evening sir\n',
 'CXM46 Kaushal Agarwal: Good evening\n',
 'Nitish Singh: Sharing the meeting link\n',
 'Nitish Singh: Timing will be shared soon\n',
 'CXM11 Shantanu Shubham: Thank you sir\n',
 'CXM46 Kaushal Agarwal: Okay sir\n',
 'Nitish Singh: If you have queries ask here\n',
 'CXM48 Anjali: Sure sir\n',
 'Nitish Singh: Resume reviews begin tomorrow\n',
 'CXM43 Bhavna Kumari: Looking forward to it\n',
 'Nitish Singh: Please fill the form\n',
 'CXM11 Shantanu Shubham: Done\n',
 'CXM46 Kaushal Agarwal: Submitted\n',
 "Nitish Singh: Today's topic is LinkedIn\n",
 'CXM48 Anjali: Great\n',
 'CXM43 Bhavna Kumari: Excited\n',
 'Nitish Singh: Keep your profiles ready\n',
 'CXM11 Shantanu Shubham: Sure\n',
 'Nitish Singh: Session starts in 5 mins\n',
 'Nitish Singh: Session started\n',
 'CXM46 Kaushal Agarwal: Useful tips\n',
 'CXM48 Anjali: Learned a lot\n',
 'Nitish Singh: Recording will be shared\n',
 'CXM43 Bhavna Kumari: Thank you sir\n',
 'Nitish Singh: Profile reviews begin now\n',
 'CXM11 Shantanu Shubham: Ready\n',
 'CXM46 Kaushal Agarwal: Waiting\n',
 'Nitish Singh: Starting with Kaushal']

In [23]:
dates = re.findall(pattern,data)
dates

['31/07/2019, 19:10 - ',
 '31/07/2019, 19:11 - ',
 '31/07/2019, 19:12 - ',
 '31/07/2019, 19:13 - ',
 '31/07/2019, 19:14 - ',
 '31/07/2019, 19:15 - ',
 '31/07/2019, 19:16 - ',
 '31/07/2019, 19:16 - ',
 '31/07/2019, 19:17 - ',
 '31/07/2019, 19:18 - ',
 '31/07/2019, 19:20 - ',
 '31/07/2019, 19:22 - ',
 '31/07/2019, 19:25 - ',
 '31/07/2019, 19:28 - ',
 '31/07/2019, 19:30 - ',
 '01/08/2019, 10:00 - ',
 '01/08/2019, 10:05 - ',
 '01/08/2019, 10:10 - ',
 '01/08/2019, 10:15 - ',
 '01/08/2019, 10:20 - ',
 '01/08/2019, 10:25 - ',
 '01/08/2019, 10:30 - ',
 '01/08/2019, 10:45 - ',
 '01/08/2019, 10:50 - ',
 '01/08/2019, 11:00 - ',
 '01/08/2019, 11:05 - ',
 '02/08/2019, 17:00 - ',
 '02/08/2019, 17:10 - ',
 '02/08/2019, 17:20 - ',
 '02/08/2019, 17:30 - ']

In [24]:
df = pd.DataFrame({
    'user_message': messages,
    'message_date': dates
})

# convert message_date type
df['message_date'] = pd.to_datetime(
    df['message_date'],
    format='%d/%m/%Y, %H:%M - '
)

df.rename(columns={'message_date': 'date'}, inplace=True)

df.head()

                                 user_message                date
0            Nitish Singh: Welcome everyone\n 2019-07-31 19:10:00
1      Nitish Singh: Session starts shortly\n 2019-07-31 19:11:00
2  CXM11 Shantanu Shubham: Good evening sir\n 2019-07-31 19:12:00
3       CXM46 Kaushal Agarwal: Good evening\n 2019-07-31 19:13:00
4    Nitish Singh: Sharing the meeting link\n 2019-07-31 19:14:00

In [25]:
 df.shape

(30, 2)

In [27]:
# separate users and messages
users = []
messages = []

for message in df['user_message']:
    entry = re.split('([\w\W]+?):\s', message)

    if entry[1:]:  # user name
        users.append(entry[1])
        messages.append(entry[2])
    else:
        users.append('group_notification')
        messages.append(entry[0])

df['user'] = users
df['message'] = messages

df.drop(columns=['user_message'], inplace=True)

df.head()

                 date                    user                     message
0 2019-07-31 19:10:00            Nitish Singh          Welcome everyone\n
1 2019-07-31 19:11:00            Nitish Singh    Session starts shortly\n
2 2019-07-31 19:12:00  CXM11 Shantanu Shubham          Good evening sir\n
3 2019-07-31 19:13:00   CXM46 Kaushal Agarwal              Good evening\n
4 2019-07-31 19:14:00            Nitish Singh  Sharing the meeting link\n

In [28]:
df['year'] = df['date'].dt.year

In [29]:
df.head()

,date,user,message,year
0,2019-07-31 19:10:00,Nitish Singh,Welcome everyone\n,2019
1,2019-07-31 19:11:00,Nitish Singh,Session starts shortly\n,2019
2,2019-07-31 19:12:00,CXM11 Shantanu Shubham,Good evening sir\n,2019
3,2019-07-31 19:13:00,CXM46 Kaushal Agarwal,Good evening\n,2019
4,2019-07-31 19:14:00,Nitish Singh,Sharing the meeting link\n,2019

In [30]:
df['date'].dt.month_name()

0       July
1       July
2       July
3       July
4       July
5       July
6       July
7       July
8       July
9       July
10      July
11      July
12      July
13      July
14      July
15    August
16    August
17    August
18    August
19    August
20    August
21    August
22    August
23    August
24    August
25    August
26    August
27    August
28    August
29    August
Name: date, dtype: object

In [32]:
df['day']=df['date'].dt.day

In [33]:
df['hour']=df['date'].dt.hour

In [34]:
 df['minute']=df['date'].dt.minute

In [35]:
 df.head()

,date,user,message,year,day,hour,minute
0,2019-07-31 19:10:00,Nitish Singh,Welcome everyone\n,2019,31,19,10
1,2019-07-31 19:11:00,Nitish Singh,Session starts shortly\n,2019,31,19,11
2,2019-07-31 19:12:00,CXM11 Shantanu Shubham,Good evening sir\n,2019,31,19,12
3,2019-07-31 19:13:00,CXM46 Kaushal Agarwal,Good evening\n,2019,31,19,13
4,2019-07-31 19:14:00,Nitish Singh,Sharing the meeting link\n,2019,31,19,14